### ISSUE TITLE
Crash when outputting results

### ISSUE THREAD

**Issue by ens-sb** [DessimozLab/omamer#30]
I am running FastOMA, and I have got a crash from omamer with the following error message:
```
Searching -  20000 queries in 6:35.2 (39.09 queries/s)
Traceback (most recent call last):
  File "/app/bin/omamer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/omamer/main.py", line 289, in main
    args.func(args)
  File "/app/lib/python3.11/site-packages/omamer/_runners.py", line 180, in search
    df = ms.merge_search(
         ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/omamer/merge_search.py", line 489, in merge_search
    return self.output_results(
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/omamer/merge_search.py", line 535, in output_results
    df["qseq_offset"] = df["qseq_offset"].astype("UInt32")
                        ~~^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/pandas/core/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'qseq_offset'
/app/lib/python3.11/site-packages/tables/file.py:113: UnclosedFileWarning: Closing remaining open file: LUCA.h5
  warnings.warn(UnclosedFileWarning(msg))
```
I would appreciate your help with this.
Botond

**Comment by alpae** [comment]
Hi @ens-sb,

could it be that you are using an old version of the LUCA.h5 database? can you test with `omamer info --db LUCA.h5` which version of the database you are using? it should be 2.0.*

if that is not correct, please update the LUCA database from https://omabrowser.org/oma/current/ . The file should be ~7.8GB. Otherwise, I need to look a bit more into this.

Best wishes
Adrian

**Comment by ens-sb** [comment]
Hi @alpae ,

Thanks for the prompt feedback! I have used the LUCA.h5 which was automatically downloaded by FastOMA from https://omabrowser.org/All/LUCA.h5 . I guess this must be the latest one.
Also, all but one proteomes successfuly completed the omamer search.

Best,
Botond

**Comment by alpae** [comment]
Hi Botond,

ok, if it works for many but one proteomes, there must be something special about this one... Are you able to share this proteome with us so that we can have a look into it more carefully?

Cheers Adrian

**Comment by ens-sb** [comment]
Hi Adrian,

I send attached the proteome which caused the trouble.

Botond
[spilosoma_lubricipeda_gca905220605v1.txt](https://github.com/DessimozLab/omamer/files/14791323/spilosoma_lubricipeda_gca905220605v1.txt)

**Comment by alpae** [comment]
oh wow, this is a nice edgecase situation. the output is generated in chunks of 10000 elements by default, and your proteome has exactly 20000 sequences. now, it tries to write an empty chunk, which fails brutally... ;-) 

as a quick fix, you can specify a different chunksize, e.g. `--chunksize 9999` instead of 10000. I will fix now as well and will release a new version. 

Thanks for reporting this.

**Comment by ens-sb** [comment]
Oh, that is a funny edge case indeed! I have excluded this proteome from my analysis for now, and will wait for the fix. Thanks for that in advance!

Botond
